language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26

licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'

script:
    - ./gradlew clean build test jacocoTestReport
    - bash <(curl https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle