language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-support
    - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'

script:
    - ./gradlew clean build test jacocoTestReport check

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle
